apt-get install tzdata
pangeo-data/pangeo-docker-images pull request #183
Opened 2021-01-23 00:39 UTC by rabernat

Adding this to our base image will fix an obscure issue that prevents prefect agents from running in our envs.

see https://github.com/PrefectHQ/prefect/issues/3061

2021-01-23 00:58 UTC, scottyhq requested changes

2021-01-23 00:58 UTC, scottyhq commented on base-image/Dockerfile
> +    && apt-get install -y wget tzdata \
no need for a new line here, just add `tzdata` after `zip` on the line above

2021-01-24 17:13 UTC, scottyhq commented
FYI - I remember @TomAugspurger opened up a similar issue a while back and it seems that just setting an environment variable did the trick (https://github.com/pangeo-data/pangeo-docker-images/issues/125). in any case, i'll merge this

`os.environ['TZ'] = 'UTC' #Just need to set default timezone`

2021-01-24 17:13 UTC, scottyhq approved these changes

2021-01-24 17:14 UTC, merged

2021-01-24 17:16 UTC, rabernat commented
Gah! I am clearly retreading a path already cleared by Tom!