Get rid of the pangeo-forge image
pangeo-data/pangeo-docker-images pull request #477
Opened 2023-08-20 02:01 UTC by yuvipanda

No longer needed as of
https://github.com/pangeo-forge/pangeo-forge-runner/pull/90!

This simplifies pangeo-forge maintenance as well, as we no longer have to match versions of python and apache_beam with whatever is going on here.

2023-08-20 22:05 UTC, weiji14 reviewed
Thanks @yuvipanda! This will simplify maintenance going forward, as we won't need to do stuff like https://github.com/pangeo-data/pangeo-docker-images/pull/470 anymore. Just some suggested changes on the main README.md and should be ok.

2023-09-11 20:37 UTC, scottyhq requested changes
Thanks @yuvipanda ! unfortunately a few conflicts now that other things have been merged. Are you able to revisit this?

2023-09-13 04:18 UTC, weiji14 commented
> I'm waiting to hear from @cisaacstern before moving forward. We all agree this is the path forward - the question now is, do we wait for [pangeo-forge/pangeo-forge-runner#90](https://github.com/pangeo-forge/pangeo-forge-runner/pull/90) to be merged before merging this, or can we do that before?

The `forge` docker images will still be archived at https://hub.docker.com/r/pangeo/forge/tags and https://quay.io/repository/pangeo/forge?tab=tags, and available for download for the forseeable future right? Should be ok to merge this PR now (once the conflicts have been resolved), since it sounds like the pangeo-forge-runner will be moving to Apache Beam supported docker images eventually.

2023-09-13 13:58 UTC, cisaacstern commented
> The forge docker images will still be archived at https://hub.docker.com/r/pangeo/forge/tags and https://quay.io/repository/pangeo/forge?tab=tags, and available for download for the forseeable future right?

How long is the foreseeable future? As long as the old images will be archived for long enough to ensure we'll have made the transition by the time the archive expires, I'm 👍

2023-09-13 18:17 UTC, yuvipanda commented on README.md
@weiji14 done!

2023-09-13 18:17 UTC, yuvipanda commented
Thanks for chiming in, @cisaacstern!

I've resolved the merge conflicts, and updated the README, @weiji14!

2023-09-13 19:25 UTC, weiji14 commented
> > The forge docker images will still be archived at https://hub.docker.com/r/pangeo/forge/tags and https://quay.io/repository/pangeo/forge?tab=tags, and available for download for the forseeable future right?
> 
> How long is the foreseeable future? As long as the old images will be archived for long enough to ensure we'll have made the transition by the time the archive expires, I'm 👍

Well, there isn't an [expiry date](https://access.redhat.com/documentation/en-us/red_hat_quay/3/html/use_red_hat_quay/working_with_tags#tag-expiration) set for the quay.io hosted images (see Expires = Never in screenshot below), so it should be until they change their terms and conditions :slightly_smiling_face:

![image](https://github.com/pangeo-data/pangeo-docker-images/assets/23487320/2714697f-f094-4477-b96e-7d2baba49486)

2023-09-13 19:26 UTC, weiji14 approved these changes
Thanks @yuvipanda! Will simplify maintenance going forward.

2023-09-13 20:26 UTC, cisaacstern commented
Awesome LGTM! Thanks all!

2023-09-13 22:22 UTC, scottyhq approved these changes

2023-09-14 00:05 UTC, merged